name: test:docs:lib

on: push

jobs:
  files-changed:
    name: Detect File Changes - docs - lib
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            docs:
              - '.github/workflows/**/*'
              - 'lib/**/*.md'
              - 'LICENSE'

#  build:
#    if: needs.files-changed.outputs.frontend == 'true'
#    name: Build - Frontend
#    needs: files-changed
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4.1.7
#      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v4.0.3
#        with:
#          node-version-file: './.tool-versions'
#      - name: Frontend | Build
#        run: npm install && npm run build
#        working-directory: ./frontend

  docs:
    if: needs.files-changed.outputs.docs == 'true'
    name: Docs - lib
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      COVERAGE_REQUIRED: 0
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4.1.7
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v4.0.3
        with:
          node-version-file: '.tool-versions'
      - name: Docs
        run: |
          npm install
          npm run docs:generate
          ./scripts/docs-coverage.sh
        working-directory: lib/