name: "test:build test docker"

on: push

jobs:
  files-changed:
    name: Detect File Changes - build - docker
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.build-docker }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            build-docker:
              - '.github/workflows/*'
              - '**/*'
  
  build-production:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build Docker Production
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4.1.7

      - name: Build Docker Production
        run: docker compose -f docker-compose.yml build
        working-directory: ${{env.WORKING_DIRECTORY}}

  #build-development:
  #  if: needs.files-changed.outputs.changes == 'true'
  #  name: Build Docker Development
  #  needs: files-changed
  #  runs-on: ubuntu-latest
  #  env:
  #    WORKING_DIRECTORY: ./
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4.1.7
  #
  #    - name: Build Docker Development
  #      run: docker compose build
  #      working-directory: ${{env.WORKING_DIRECTORY}}